package com.spring.entity;
// Generated May 5, 2015 11:51:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Manufacture generated by hbm2java
 */
@Entity
@Table(name="manufacture"
    ,catalog="spring"
)
public class Manufacture  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String address;
     private String contactno;

    public Manufacture() {
    }

    public Manufacture(String name, String address, String contactno) {
       this.name = name;
       this.address = address;
       this.contactno = contactno;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="address", length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="contactno", length=45)
    public String getContactno() {
        return this.contactno;
    }
    
    public void setContactno(String contactno) {
        this.contactno = contactno;
    }




}


